name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions needed for the GitHub Pages Deploy Action
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pytest pytest-cov
    
    - name: Run unit tests
      run: |
        mkdir -p test-results/python
        # Count tests first
        echo "UNIT_COUNT=$(pytest tests/unit --collect-only -q | wc -l | xargs)" >> $GITHUB_ENV
        # Run tests (may fail but we'll continue)
        set +e
        pytest tests/unit -v
        unit_test_exit=$?
        set -e
        echo "UNIT_TEST_EXIT=$unit_test_exit" >> $GITHUB_ENV
    
    - name: Run integration tests
      if: always()
      run: |
        # Count tests first
        echo "INTEGRATION_COUNT=$(pytest tests/integration --collect-only -q | wc -l | xargs)" >> $GITHUB_ENV
        # Run tests (may fail but we'll continue)
        set +e
        pytest tests/integration -v
        integration_test_exit=$?
        set -e
        echo "INTEGRATION_TEST_EXIT=$integration_test_exit" >> $GITHUB_ENV
    
    - name: Run coverage report
      if: always()
      run: |
        mkdir -p test-results/python/coverage
        # Try to run coverage, but don't fail if tests fail
        set +e
        pytest --cov=. --cov-report=xml --cov-report=term-missing --cov-report=html:test-results/python/coverage
        cov_exit_code=$?
        set -e
        
        # Extract coverage percentage if the file exists
        if [ -f "coverage.xml" ]; then
          echo "COVERAGE_PCT=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(round(float(root.attrib['line-rate']) * 100))")" >> $GITHUB_ENV
        else
          echo "COVERAGE_PCT=0" >> $GITHUB_ENV
          # Create a placeholder coverage report
          echo '<html><body><h1>No Coverage Report Available</h1><p>Tests failed to run properly.</p></body></html>' > test-results/python/coverage/index.html
        fi
    
    - name: Generate test stats badge
      if: always()
      run: |
        mkdir -p test-results/python
        
        # Set defaults if tests failed
        if [ -z "$UNIT_COUNT" ]; then
          echo "UNIT_COUNT=0" >> $GITHUB_ENV
        fi
        
        if [ -z "$INTEGRATION_COUNT" ]; then
          echo "INTEGRATION_COUNT=0" >> $GITHUB_ENV
        fi
        
        if [ -z "$COVERAGE_PCT" ]; then
          echo "COVERAGE_PCT=0" >> $GITHUB_ENV
        fi
        
        # Create badge for test count and coverage
        cat > test-results/python/badge-stats.json << EOF
        {
          "schemaVersion": 1,
          "label": "Tests",
          "message": "${{ env.UNIT_COUNT }} unit, ${{ env.INTEGRATION_COUNT }} integration, ${{ env.COVERAGE_PCT }}% coverage",
          "color": "$([ ${{ env.COVERAGE_PCT }} -ge 80 ] && echo 'success' || ([ ${{ env.COVERAGE_PCT }} -ge 60 ] && echo 'yellow' || echo 'critical'))"
        }
        EOF
        
        # Create badge for coverage only
        cat > test-results/python/badge-coverage.json << EOF
        {
          "schemaVersion": 1,
          "label": "Coverage",
          "message": "${{ env.COVERAGE_PCT }}%",
          "color": "$([ ${{ env.COVERAGE_PCT }} -ge 80 ] && echo 'success' || ([ ${{ env.COVERAGE_PCT }} -ge 60 ] && echo 'yellow' || echo 'critical'))"
        }
        EOF
        
        # Create badge for workflow status
        cat > test-results/python/badge-status.json << EOF
        {
          "schemaVersion": 1,
          "label": "Status",
          "message": "${{ job.status }}",
          "color": "${{ job.status == 'success' && 'success' || 'critical' }}"
        }
        EOF
        
        ls -la test-results/python
    
    - name: Deploy test results to test-results branch
      if: always() && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: test-results
        target-folder: test-results
        branch: test-results
        clean: false
    
    - name: Upload test coverage as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: python-coverage
        path: test-results/python/coverage/
        retention-days: 30